### ISSUE TITLE
Some packages can't be found and eksctl fails

### ISSUE THREAD

**Issue by sgulbetekin** [kalawat1985/eks-kubeflow-cloudformation-quick-start#1]
Hi,

I have run the CFN template in eu-west-1 (twice) and got the same errors both time.

https://pastebin.com/2XL6rGs2

Please have a look.
Also when you run multiple times, some values are hardcoded like cluster name, KMS key alias, keypair name, would be nice to add a random value at the end.

Best regards,
Serhat

**Comment by kalawat1985** [comment]
Hi Serhat, I am checking on this and will get back to you soon.

**Comment by kalawat1985** [comment]
Have pushed changes to cf.json and tested in Ireland region. It should work now.
